language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - pypy
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "if [[ ! $TRAVIS_PYTHON_VERSION =~ ^3\\. ]]; then pip install --use-mirrors boto; fi"
  - "pip install --use-mirrors ."
script:
  - py.test
