language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - pypy
install:
  - pip install -q -e --use-mirrors .
  - pip install -q --use-mirrors pytest
  - pip install -q --use-mirrors flexmock
script:
  - py.test
